language: python
sudo: required
services:
- docker
python:
- '3.6'
script:
- "./build.sh"
after_script:
- docker images
before_deploy:
- echo "$DOCKER_PASSWORD" | docker login --password-stdin --username "$DOCKER_USERNAME"
after_deploy:
- docker logout
deploy:
  provider: script
  script:
  - "./publish.sh"
env:
  global:
    # DOCKER_PASSWORD
  - secure: Z/DoDlXBobIGxXsyR/BHxthd/mcXv0RY3V43yXLr4WHOaAqDL9TaIApNrNnrkwSqyEyrC61vxf0J0EBrNLnJbhhtOdQj7TqjSuGJSOuGwuKx62qunYnwUcjMMeIvel1eLsrALetPfXfoCitlJ2Hgpo6B4bVeovdiTB0CexPOMKqj5i+yLFtrWvX6yfxLSfDX2DLSfo2BHH3JJEf0h2R/wp/YaIjUK5GeFFmtW6B9kD2VJlVvifOPnB4D1VKcXk/mMRTAnq90G6vPYc1835Z7oo816brLMQ5cy6BCnopTq6QwxKzLP7cT8nZ4t93xmgg/QOJvMPOe+ZUunxY3+X5n9eMfBnEKChTUwMdm0BftBdgOhV0zbiiYqA+9c+9hAVKZ6AfX+IChdVBuQiAwcrf/pa2PTo8uROt/x9fZ2O+cfPLFJJgXhMtNbj/Y6l0Q45tDy8HkYNXhXJxCe0c/hdnorYAXKfqFfX+OLL12NZhDzEgsZNI4eJm0aNM/mwefvRLHQ0cj/kuOjoYg8wQy4cDFtfOmZ0T0QfvlDpMzAeCVfml3w1lvtljzvubhgW2sYTuiuYAJ320UofPJOcRLPilwgziiNDvgKHR01CzEjEPJ72ECu6U/pde6u7+RFVfECs6sOzs2WP9OknwjBHPuQIXwRRwkzQOmi/eGzMDkuQ/C08s=
    # DOCKER USERNAME
  - secure: tWkyIvf1DWTmHigM9CVbQj5b3B3VwOf1/rmYIvNqJp75xGHo4xVjom+8BmDim9fRWWODdEwDTS/GrbCcB/BcZOQsnTxpHB27PoYVOM1tlz2vZ2tFVywuKzpEiC8VDoO/aZKbn49RivZcSvg59nJf+zifC4zEWtT/Fg9sCQ+HeB58YTLEgvaNG32aa7OaGiiptvwgzv603cU2zguvgJXFGQnKeZddRhznLDJDr9WjN2ibw/M5ERFL/lJ7ydNWTEOguou/9SblJq1ilpI4glCNhHGao+1jAuihq8GSxVeVa/yF+y6hEKcR2SxzffKtqRRa4xxvXu+1ahPi0ZLw8aWPAphozwvizccAB/v0YTRZb0dkyl9Ljz7m+UP4rgytUeTeE+mqn0KXnHDSgXuzK+ChVgHGrXGCwDAisr0wX8IJf1OsYpEv2ekKRXAhizgnXXP+JhTBddeIkwIMh82O2Tf++91MKAg+NIb/jL2k+RlwetSxIAsAzmo4/tZqONKTCTfWpxWJEKXoA+KJo73eGqII9ESVHpala74RFMl5Lt3EqKseiWo+wtbKEhi5LD3W1ARKHrAsSh/Xcxof9ThQHiiesua1qYY9qfZvbkNqqTv3Ama0hOiG0QbIRglwMUMBgtby3z1qDtVcGCtxpmCpcK4FlRJfzT0snbtKTG0kQtUPvgo=
