language: python
sudo: required
services:
- docker
python:
- '3.6'
before_install:
- docker pull plexinc/pms-docker
install:
- "./build.sh"
script:
- docker login --password ${DOCKER_PASSWORD} --username salimfadhley
- "./publish.sh"
- docker logout
env:
  matrix:
    secure: 2V5HL5SQc71pWD2POv41jh/S0exehxcy+pV7GY11l2g0r8BELsU413+mP6sifHGcjJJSfZfOuou2CEuUdFfAoMzWKmt85jSefOqXdXQhgyUxacbxPuu6Jr9hdXO+8t/BR4cIimGyk/3WUh1kyrNunquUE7Dmpr1AIGnIDwithrrgrQr7X9eb2I3IXDRVhnERfMQJVHx/4t8OT/CYh5NFcdCQLGf9YSz74eV1ycJ7Lh3R52bw/irnKF2ZbiX6JcK8xZKqUFlM8dzFCkBxgYlaiEYFn9Zj6N5XCT+Z9GSm+5oFb5HKIgkMG/LjaD1b1ak5e2qqYjY6MxkQAmLbsPyVwGN/bri1waUOOsaGa50uJ/G5cnQGmPatWpaUXyNQuRQCxYzWBnlKIThO2w6hvfvnURfkuQ9OMigQf7lbr1Bd6S3BUqQgnplYWgc/B4LnoYq5QScK2IxVbEFAIdF6GmEq83MVHm/tSQVEZyzdLjivkkYSLt9NUqUn5trpAjQW2WyFRHIv8OYvDolQ5YexMLHBRkJO/lZg798QvGs6Pwsfdx2ra7SC0gxepR9PB86b09N36u52ztnzW9PwP4mej7baWyDjLFJfEcPQLwfeT5394OdcHs4FIy1zU1xPTL21EzjUYEEYYE8rL+e1pKATgtJSY0nUYmJO2EbUjBAguveLFSc=
